# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:7411/spring_db
spring.datasource.username=postgres
spring.datasource.password=shri2510
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool (HikariCP Defaults)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000